name: Install tmux
description: Installs tmux on supported OSes
runs:
  using: composite
  steps:
    - name: Install tmux (Linux)
      if: ${{ runner.os == 'ubuntu-latest' }}
      shell: bash
      run: |
          sudo apt-get update
          sudo apt-get install -y tmux

    - name: Install tmux (Mac)
      if: ${{ runner.os == 'macos-latest' }}
      shell: bash
      run: |
          brew install tmux
