name: Benchmark
on:
  - pull_request
  - workflow_call
  - workflow_dispatch
jobs:
  benchmark:
    name: Benchmark
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
          # - runs-on: macos-latest
          # - runs-on: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/detect-and-install-rust-toolchain

      - uses: ./.github/actions/install-buildit

      - name: Cache tmp.sample
        uses: actions/cache@v3
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: ./tmp.sample
          key: tmp.sample-${{ github.job }}
          restore-keys: tmp.sample-${{ github.job }}

      - name: Run all benchmarks
        run: buildit benchmark --bench-names directory_item_build directory_item_build_x2 directory_item_build_x3
